language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

script:
  - ./go.test.sh
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)